apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-management
spec:
  type: NodePort
  ports:
  - targetPort: 15672
    port: 15672
    nodePort: 30002
  selector:
    component: rabbitmq
